#!/system/bin/sh

CONFIG_JSON=/system/Synapse/synapse/config.json;
ACTION_SCRIPTS=/system/Synapse/synapse/actions/;

if [ ! -f $CONFIG_JSON ]; then
  mount -t rootfs -o rw,remount rootfs;
  chmod -R 755 $ACTION_SCRIPTS;
  source /system/Synapse/synapse/config.json.generate > $CONFIG_JSON;
  mount -t rootfs -o ro,remount rootfs;
fi;

case "${1}" in
  config)
	cat $CONFIG_JSON;;
  configpath)
	echo $CONFIG_JSON;;
  actionpath)
	echo $ACTION_SCRIPTS;;
esac;
